INSERT INTO university (name, uni_domain, city) VALUES
('Adana Alparslan Türkeş Bilim ve Teknoloji Üniversitesi', 'atu.edu.tr', 'Adana'),
('Adana Bilim ve Teknoloji Üniversitesi', 'adanabtu.edu.tr', 'Adana'),
('Adıyaman Üniversitesi', 'adiyaman.edu.tr', 'Adıyaman'),
('Afyon Kocatepe Üniversitesi', 'aku.edu.tr', 'Afyonkarahisar'),
('Afyonkarahisar Sağlık Bilimleri Üniversitesi', 'afsu.edu.tr', 'Afyonkarahisar'),
('Ağrı İbrahim Çeçen Üniversitesi', 'agri.edu.tr', 'Ağrı'),
('Aksaray Üniversitesi', 'aksaray.edu.tr', 'Aksaray'),
('Amasya Üniversitesi', 'amasya.edu.tr', 'Amasya'),
('Ankara Üniversitesi', 'ankara.edu.tr', 'Ankara'),
('Ankara Hacı Bayram Veli Üniversitesi', 'hbv.edu.tr', 'Ankara'),
('Ankara Müzik ve Güzel Sanatlar Üniversitesi', 'mgu.edu.tr', 'Ankara'),
('Ankara Yıldırım Beyazıt Üniversitesi', 'aybu.edu.tr', 'Ankara'),
('Ardahan Üniversitesi', 'ardahan.edu.tr', 'Ardahan'),
('Artvin Çoruh Üniversitesi', 'artvin.edu.tr', 'Artvin'),
('Atatürk Üniversitesi', 'atauni.edu.tr', 'Erzurum'),
('Balıkesir Üniversitesi', 'balikesir.edu.tr', 'Balıkesir'),
('Bandırma Onyedi Eylül Üniversitesi', 'bandirma.edu.tr', 'Balıkesir'),
('Bartın Üniversitesi', 'bartin.edu.tr', 'Bartın'),
('Batman Üniversitesi', 'batman.edu.tr', 'Batman'),
('Bayburt Üniversitesi', 'bayburt.edu.tr', 'Bayburt'),
('Bilecik Şeyh Edebali Üniversitesi', 'bilecik.edu.tr', 'Bilecik'),
('Bingöl Üniversitesi', 'bingol.edu.tr', 'Bingöl'),
('Bitlis Eren Üniversitesi', 'beu.edu.tr', 'Bitlis'),
('Boğaziçi Üniversitesi', 'boun.edu.tr', 'İstanbul'),
('Bolu Abant İzzet Baysal Üniversitesi', 'ibu.edu.tr', 'Bolu'),
('Bursa Teknik Üniversitesi', 'btu.edu.tr', 'Bursa'),
('Bursa Uludağ Üniversitesi', 'uludag.edu.tr', 'Bursa'),
('Çanakkale Onsekiz Mart Üniversitesi', 'comu.edu.tr', 'Çanakkale'),
('Çankırı Karatekin Üniversitesi', 'karatekin.edu.tr', 'Çankırı'),
('Çukurova Üniversitesi', 'cu.edu.tr', 'Adana'),
('Dicle Üniversitesi', 'dicle.edu.tr', 'Diyarbakır'),
('Dokuz Eylül Üniversitesi', 'deu.edu.tr', 'İzmir'),
('Düzce Üniversitesi', 'duzce.edu.tr', 'Düzce'),
('Ege Üniversitesi', 'ege.edu.tr', 'İzmir'),
('Erciyes Üniversitesi', 'erciyes.edu.tr', 'Kayseri'),
('Erzincan Binali Yıldırım Üniversitesi', 'erzincan.edu.tr', 'Erzincan'),
('Erzurum Teknik Üniversitesi', 'erzurum.edu.tr', 'Erzurum'),
('Eskişehir Osmangazi Üniversitesi', 'ogu.edu.tr', 'Eskişehir'),
('Eskişehir Teknik Üniversitesi', 'eskisehir.edu.tr', 'Eskişehir'),
('Fırat Üniversitesi', 'firat.edu.tr', 'Elazığ'),
('Galatasaray Üniversitesi', 'gsu.edu.tr', 'İstanbul'),
('Gazi Üniversitesi', 'gazi.edu.tr', 'Ankara'),
('Gaziantep Üniversitesi', 'gantep.edu.tr', 'Gaziantep'),
('Gebze Teknik Üniversitesi', 'gtu.edu.tr', 'Kocaeli'),
('Giresun Üniversitesi', 'giresun.edu.tr', 'Giresun'),
('Gümüşhane Üniversitesi', 'gumushane.edu.tr', 'Gümüşhane'),
('Hacettepe Üniversitesi', 'hacettepe.edu.tr', 'Ankara'),
('Hakkari Üniversitesi', 'hakkari.edu.tr', 'Hakkari'),
('Harran Üniversitesi', 'harran.edu.tr', 'Şanlıurfa'),
('Hatay Mustafa Kemal Üniversitesi', 'mku.edu.tr', 'Hatay'),
('Hitit Üniversitesi', 'hitit.edu.tr', 'Çorum'),
('Iğdır Üniversitesi', 'igdir.edu.tr', 'Iğdır'),
('İnönü Üniversitesi', 'inonu.edu.tr', 'Malatya'),
('İskenderun Teknik Üniversitesi', 'iste.edu.tr', 'Hatay'),
('İstanbul Medeniyet Üniversitesi', 'medeniyet.edu.tr', 'İstanbul'),
('İstanbul Üniversitesi', 'istanbul.edu.tr', 'İstanbul'),
('İstanbul Üniversitesi-Cerrahpaşa', 'istanbultip.edu.tr', 'İstanbul'),
('İstanbul Teknik Üniversitesi', 'itu.edu.tr', 'İstanbul'),
('İzmir Kâtip Çelebi Üniversitesi', 'ikcu.edu.tr', 'İzmir'),
('İzmir Demokrasi Üniversitesi', 'idu.edu.tr', 'İzmir'),
('Kafkas Üniversitesi', 'kafkas.edu.tr', 'Kars'),
('Kahramanmaraş Sütçü İmam Üniversitesi', 'ksu.edu.tr', 'Kahramanmaraş'),
('Karabük Üniversitesi', 'karabuk.edu.tr', 'Karabük'),
('Karadeniz Teknik Üniversitesi', 'ktu.edu.tr', 'Trabzon'),
('Karamanoğlu Mehmetbey Üniversitesi', 'kmu.edu.tr', 'Karaman'),
('Kastamonu Üniversitesi', 'kastamonu.edu.tr', 'Kastamonu'),
('Kayseri Üniversitesi', 'kayseri.edu.tr', 'Kayseri'),
('Kırıkkale Üniversitesi', 'kku.edu.tr', 'Kırıkkale'),
('Kırklareli Üniversitesi', 'klu.edu.tr', 'Kırklareli'),
('Kilis 7 Aralık Üniversitesi', 'kilis.edu.tr', 'Kilis'),
('Kocaeli Üniversitesi', 'kocaeli.edu.tr', 'Kocaeli'),
('Konya Teknik Üniversitesi', 'ktun.edu.tr', 'Konya'),
('Kütahya Dumlupınar Üniversitesi', 'dpu.edu.tr', 'Kütahya'),
('Manisa Celal Bayar Üniversitesi', 'cbu.edu.tr', 'Manisa'),
('Mardin Artuklu Üniversitesi', 'artuklu.edu.tr', 'Mardin'),
('Marmara Üniversitesi', 'marmara.edu.tr', 'İstanbul'),
('Mersin Üniversitesi', 'mersin.edu.tr', 'Mersin'),
('Muğla Sıtkı Koçman Üniversitesi', 'mu.edu.tr', 'Muğla'),
('Munzur Üniversitesi', 'munzur.edu.tr', 'Tunceli'),
('Nevşehir Hacı Bektaş Veli Üniversitesi', 'nevsehir.edu.tr', 'Nevşehir'),
('Niğde Ömer Halisdemir Üniversitesi', 'ohu.edu.tr', 'Niğde'),
('Ondokuz Mayıs Üniversitesi', 'omu.edu.tr', 'Samsun'),
('Ordu Üniversitesi', 'odu.edu.tr', 'Ordu'),
('Orta Doğu Teknik Üniversitesi', 'metu.edu.tr', 'Ankara'),
('Osmaniye Korkut Ata Üniversitesi', 'osmaniye.edu.tr', 'Osmaniye'),
('Pamukkale Üniversitesi', 'pau.edu.tr', 'Denizli'),
('Recep Tayyip Erdoğan Üniversitesi', 'erdogan.edu.tr', 'Rize'),
('Sakarya Üniversitesi', 'sakarya.edu.tr', 'Sakarya'),
('Sakarya Uygulamalı Bilimler Üniversitesi', 'subu.edu.tr', 'Sakarya'),
('Selçuk Üniversitesi', 'selcuk.edu.tr', 'Konya'),
('Siirt Üniversitesi', 'siirt.edu.tr', 'Siirt'),
('Sinop Üniversitesi', 'sinop.edu.tr', 'Sinop'),
('Sivas Cumhuriyet Üniversitesi', 'cumhuriyet.edu.tr', 'Sivas'),
('Sivas Bilim ve Teknoloji Üniversitesi', 'sivas.edu.tr', 'Sivas'),
('Şırnak Üniversitesi', 'sirnak.edu.tr', 'Şırnak'),
('Tokat Gaziosmanpaşa Üniversitesi', 'gop.edu.tr', 'Tokat'),
('Trakya Üniversitesi', 'trakya.edu.tr', 'Edirne'),
('Uşak Üniversitesi', 'usak.edu.tr', 'Uşak'),
('Van Yüzüncü Yıl Üniversitesi', 'yyu.edu.tr', 'Van'),
('Yalova Üniversitesi', 'yalova.edu.tr', 'Yalova'),
('Yozgat Bozok Üniversitesi', 'bozok.edu.tr', 'Yozgat'),
('Yıldız Teknik Üniversitesi', 'ytu.edu.tr', 'İstanbul'),
('Zonguldak Bülent Ecevit Üniversitesi', 'beun.edu.tr', 'Zonguldak'),

-- VAKIF ÜNİVERSİTELERİ
('Acıbadem Mehmet Ali Aydınlar Üniversitesi', 'acibadem.edu.tr', 'İstanbul'),
('Altınbaş Üniversitesi', 'altinbas.edu.tr', 'İstanbul'),
('Atılım Üniversitesi', 'atilim.edu.tr', 'Ankara'),
('Avrasya Üniversitesi', 'avrasya.edu.tr', 'Trabzon'),
('Bahçeşehir Üniversitesi', 'bau.edu.tr', 'İstanbul'),
('Başkent Üniversitesi', 'baskent.edu.tr', 'Ankara'),
('Beykent Üniversitesi', 'beykent.edu.tr', 'İstanbul'),
('Bezmialem Vakıf Üniversitesi', 'bezmialem.edu.tr', 'İstanbul'),
('Biruni Üniversitesi', 'biruni.edu.tr', 'İstanbul'),
('Bilkent Üniversitesi', 'bilkent.edu.tr', 'Ankara'),
('Çağ Üniversitesi', 'cag.edu.tr', 'Mersin'),
('Çankaya Üniversitesi', 'cankaya.edu.tr', 'Ankara'),
('Doğuş Üniversitesi', 'dogus.edu.tr', 'İstanbul'),
('Fatih Sultan Mehmet Vakıf Üniversitesi', 'fsm.edu.tr', 'İstanbul'),
('Fenerbahçe Üniversitesi', 'fbu.edu.tr', 'İstanbul'),
('Gedik Üniversitesi', 'gedik.edu.tr', 'İstanbul'),
('İstanbul Gelişim Üniversitesi', 'gelisim.edu.tr', 'İstanbul'),
('Haliç Üniversitesi', 'halic.edu.tr', 'İstanbul'),
('Hasan Kalyoncu Üniversitesi', 'hku.edu.tr', 'Gaziantep'),
('Işık Üniversitesi', 'isikun.edu.tr', 'İstanbul'),
('İbn Haldun Üniversitesi', 'ihu.edu.tr', 'İstanbul'),
('İstanbul 29 Mayıs Üniversitesi', '29mayis.edu.tr', 'İstanbul'),
('İstanbul Arel Üniversitesi', 'arel.edu.tr', 'İstanbul'),
('İstanbul Atlas Üniversitesi', 'atlas.edu.tr', 'İstanbul'),
('İstanbul Aydın Üniversitesi', 'aydin.edu.tr', 'İstanbul'),
('İstanbul Bilgi Üniversitesi', 'bilgi.edu.tr', 'İstanbul'),
('İstanbul Esenyurt Üniversitesi', 'esenyurt.edu.tr', 'İstanbul'),
('İstanbul Galata Üniversitesi', 'galata.edu.tr', 'İstanbul'),
('İstanbul Kavram Üniversitesi', 'kavram.edu.tr', 'İstanbul'),
('İstanbul Kent Üniversitesi', 'kent.edu.tr', 'İstanbul'),
('İstanbul Kültür Üniversitesi', 'iku.edu.tr', 'İstanbul'),
('İstanbul Medipol Üniversitesi', 'medipol.edu.tr', 'İstanbul'),
('İstanbul Okan Üniversitesi', 'okan.edu.tr', 'İstanbul'),
('İstanbul Rumeli Üniversitesi', 'rumeli.edu.tr', 'İstanbul'),
('İstanbul Sabahattin Zaim Üniversitesi', 'izu.edu.tr', 'İstanbul'),
('İstinye Üniversitesi', 'istinye.edu.tr', 'İstanbul'),
('Kadir Has Üniversitesi', 'khas.edu.tr', 'İstanbul'),
('Karatay Üniversitesi', 'karatay.edu.tr', 'Konya'),
('Koç Üniversitesi', 'ku.edu.tr', 'İstanbul'),
('Konya Gıda ve Tarım Üniversitesi', 'gidatarim.edu.tr', 'Konya'),
('Lokman Hekim Üniversitesi', 'lokmanhekim.edu.tr', 'Ankara'),
('Maltepe Üniversitesi', 'maltepe.edu.tr', 'İstanbul'),
('MEF Üniversitesi', 'mef.edu.tr', 'İstanbul'),
('Nişantaşı Üniversitesi', 'nisantasi.edu.tr', 'İstanbul'),
('Nuh Naci Yazgan Üniversitesi', 'nny.edu.tr', 'Kayseri'),
('Özyeğin Üniversitesi', 'ozyegin.edu.tr', 'İstanbul'),
('Piri Reis Üniversitesi', 'pirireis.edu.tr', 'İstanbul'),
('Sabancı Üniversitesi', 'sabanciuniv.edu', 'İstanbul'),
('Sanko Üniversitesi', 'sanko.edu.tr', 'Gaziantep'),
('TED Üniversitesi', 'tedu.edu.tr', 'Ankara'),
('Toros Üniversitesi', 'toros.edu.tr', 'Mersin'),
('Türk Hava Kurumu Üniversitesi', 'thk.edu.tr', 'Ankara'),
('Ufuk Üniversitesi', 'ufuk.edu.tr', 'Ankara'),
('Üsküdar Üniversitesi', 'uskudar.edu.tr', 'İstanbul'),
('Yeditepe Üniversitesi', 'yeditepe.edu.tr', 'İstanbul'),
('Yüksek İhtisas Üniversitesi', 'yiu.edu.tr', 'Ankara'),
('Yeni Yüzyıl Üniversitesi', 'yeniyuzyil.edu.tr', 'İstanbul');
